### ISSUE TITLE
M1 (or Big Sur) causes SIP & XProtect Alert

### ISSUE THREAD

**Issue by macitpros** [macitpros/wm-silnite#12]
Could be Big Sur or M1 (unknown at this time) trigging one-time alert `200`
```
SIP or XProtect is disabled! 
XProtect is disabled (boo) 
SIP is disabled (boohoo)
```
On every daily report.

**Comment by macitpros** [comment]
Found it was `silnite` needed an update to make it compatible with M1 Mac computers.

Update released https://eclecticlight.co/2021/12/15/silnite-6-is-fully-compatible-with-m1-macs-and-monterey/comment-page-1/#comment-68781

**Comment by dircadmin** [comment]
It still shows "SIP is disabled" for every Mac that I run it on. Those are all kind of models, from 2012 to 2022.. 
I'm running the latest versions of wm-silnite and silnite (6).

**Comment by macitpros** [comment]
Yes, the newer version of `silnite` was released, but there were some changes in reporting (specifically what to grep from the result). Update to the plugin will be forth coming, when some free time presents itself.

**Comment by macitpros** [comment]
Currently testing https://github.com/macitpros/wm-silnite/tree/silnite6-compatibility branch for silnite 6 compatibility.

**Comment by dircadmin** [comment]
Thanks, I will test it immediately because Watchman ignores the muting for the plugin so I get a lot of alerts in my inbox recently.

**Comment by dircadmin** [comment]
OK, the alerts keep coming in even with a muted plugin and Version 7.0.1 of wm-silnite.
Also it reports both, XProtect and SIP as disabled on my M1 MaxBook even though Silentknight shows only green checkmarks. 
Can I help you with anything like logs or tests?

**Comment by dircadmin** [comment]
OK, i fixed it by exchanging enabled and aktiv in the plugin at two places. Now it's working like a charm.
